models:
  gpt2: openai-community/gpt2
  gpt2-medium: openai-community/gpt2-medium
  gpt2-large: openai-community/gpt2-large
  gpt2-q: openai-community/gpt2
  gpt3: minhtoan/gpt3-small-finetune-cnndaily-news
  chat: Sharathhebbar24/chat_gpt2
  chat2: h2oai/h2o-danube3-500m-chat
  pythia1b: EleutherAI/pythia-1b
  deepseek: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
  deepseek-coder: deepseek-ai/deepseek-coder-1.3b-instruct
  deepseek-math: VladShash/deepseek-math-7b-lean-prover-dpo-olmo-3
  qwen3-math: jaygala24/Qwen3-1.7B-ReMax-math-reasoning
  tiny-llama: alexredna/TinyLlama-1.1B-Chat-v1.0-reasoning-v2