models:
  gpt2: openai-community/gpt2
  gpt2-medium: openai-community/gpt2-medium
  gpt2-large: openai-community/gpt2-large
  chat: Sharathhebbar24/chat_gpt2
  chat2: model-load h2oai/h2o-danube3-500m-chat
  pythia1b: EleutherAI/pythia-1b
  deepseek: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
  deepseek-coder: deepseek-ai/deepseek-coder-1.3b-instruct